apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketbase
  namespace: devops-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketbase
  template:
    metadata:
      labels:
        app: pocketbase
    spec:
      containers:
        - name: pocketbase
          image: ghcr.io/muchobien/pocketbase:0.22.4
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: data
              mountPath: /pb/pb_data
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pocketbase-data
